name: update-cache

on:
  schedule:
    # Daily at 13:00 UTC, 07:00 US Central
    - cron: "0 13 * * *"

  # Enables the web UI manual trigger, handy for oneoff runs
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  update-cache:
    name: update-cache
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Node setup
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    - name: Update cached data
      run: |
        npm run update-cached-mods
        npm run update-cached-items
        npm run update-cached-weapon-wish-lists

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: updates cached data"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: "feat: update cached data"
        reviewers: "@cujarrett"
